version: '3.8'

services:
  chatroom:
    build: .
    container_name: go-chatroom
    ports:
      - "8080:8080"
    environment:
      - CHATROOM_HOST=0.0.0.0
      - CHATROOM_PORT=8080
      - CHATROOM_MAX_USERS=100
      - CHATROOM_TIMEOUT=40
      - CHATROOM_LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatroom-network

  # 可选：Redis用于扩展功能（如消息持久化）
  redis:
    image: redis:7-alpine
    container_name: chatroom-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - chatroom-network
    profiles:
      - extended

networks:
  chatroom-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
